language: c
compiler:
 - gcc
env:
  global:
   - LUAROCKS_BASE=luarocks-2.2.2
   - HARFBUZZ_BASE=harfbuzz-0.9.26
  matrix:
   - LUA_VER=5.3 LUA_52_COMPAT=true LUA_53_BASE=lua-5.3.1
   - LUA_VER=5.3 LUA_52_COMPAT=false LUA_53_BASE=lua-5.3.1
   - LUA_VER=5.2
   - LUA_VER=5.1
before_install:
 - export LUA_PKG=lua$LUA_VER LUA_DEV=liblua$LUA_VER-dev LUA_SFX=$LUA_VER
   # Utility function for installing Noto fonts into the test environment
 - get_noto () {
     mkdir -p ~/.fonts;
     curl -Ls https://noto-website.storage.googleapis.com/pkgs/Noto$1-hinted.zip > $1.zip;
     unzip -d ~/.fonts -n $1.zip;
   }
 - sudo apt-get update -qq
   # Sadly Lua 5.3 is not available from any PPA for Ubuntu 12.04 LTS (used by Travis)
 - if [ $LUA_VER = 5.3 ]; then
      sudo apt-get install libreadline-dev;
      wget http://www.lua.org/ftp/$LUA_53_BASE.tar.gz;
      tar xfz $LUA_53_BASE.tar.gz && pushd $LUA_53_BASE;
      $LUA_52_COMPAT || sed 's/-DLUA_COMPAT_5_2 //' -i src/Makefile;
      make linux && sudo make install && popd;
      wget -O lualib.tar.gz 'http://sourceforge.net/projects/luabinaries/files/5.3/Linux%20Libraries/lua-5.3_Linux313_64_lib.tar.gz/download';
      tar xfz lualib.tar.gz liblua53.so;
      sudo cp liblua53.so /usr/local/lib/;
      export LUA_INCDIR=/usr/local/include LUA_CONFIGURE_ARGS=(--lua-version=$LUA_VER --lua-suffix=$LUA_SFX --with-lua-include=$LUA_INCDIR);
   else
      sudo apt-get install -y $LUA_PKG $LUA_DEV;
      export LUA_INCDIR=/usr/include/lua$LUA_VER;
   fi
   # Install devel libraries and headers (for compiling libtexpdf)
 - sudo apt-get install -y lib{freetype6,fontconfig1,png,expat1}-dev
   # Install fonts (needed for typesetting regression tests)
 - sudo apt-get install -y fonts-{linuxlibertine,sil-{scheherazade,gentium{,-basic}}}
   # Install luarocks (to later fetch SILE runtime dependencies)
 - get_noto NaskhArabic && get_noto SansKannada
 - wget http://luarocks.org/releases/$LUAROCKS_BASE.tar.gz
 - tar xfz $LUAROCKS_BASE.tar.gz && pushd $LUAROCKS_BASE
 - ./configure $LUA_CONFIGURE_ARGS && sudo make && sudo make install && popd
 - wget http://www.freedesktop.org/software/harfbuzz/release/$HARFBUZZ_BASE.tar.bz2
 - tar xfj $HARFBUZZ_BASE.tar.bz2 && pushd $HARFBUZZ_BASE
 - ./configure && make && sudo make install && popd
 - sudo ldconfig
   # Install SILE runtime dependencies
 - sudo luarocks install lpeg
 - sudo luarocks install luaexpat
 - sudo luarocks install lua_cliargs 2.3-3
 - sudo luarocks install busted
script:
 - ./bootstrap.sh && ./configure && make
 - busted -m './lua-libraries/?.lua;./lua-libraries/?/init.lua' tests
 - ./tests/attack.pl
 - ./tests/attack.pl --regression
