language: c
sudo: false
compiler:
 - gcc
addons:
 apt:
  packages:
   - libgraphite2-dev
   - libicu-dev
   - libreadline-dev
   - libfreetype6-dev
   - libfontconfig1-dev
   - libpng-dev
   - libexpat1-dev
   - lua5.2
   - liblua5.2-dev
   - lua-filesystem
   - luarocks
env:
  global:
   - LUAROCKS_BASE=luarocks-2.2.2
   - HARFBUZZ_BASE=harfbuzz-1.0.4
   - GRAPHITE=true
   - ICU=true
  matrix:
   - LUA_VER=5.2
   - LUA_VER=5.2 GRAPHITE=false
before_install:
 - export LUA_PKG=lua$LUA_VER LUA_DEV=liblua$LUA_VER-dev LUA_SFX=$LUA_VER
 - if $ICU; then
      curl -s -L https://gist.githubusercontent.com/alerque/1ad04c9502d8eafebffb/raw/8476ea675f6778f26635afbb946ec3cecd66d12a/icu_pkgconfig_files.tar | base64 -d | sudo tar xP;
   fi
 - export LUA_INCDIR=/usr/include/lua$LUA_VER;
 - cd ~/.fonts && wget http://dealer.simon-cozens.org/~simon/tmp/silefonts.tar.gz && tar xvf silefonts.tar.gz && popd
 - wget http://www.freedesktop.org/software/harfbuzz/release/$HARFBUZZ_BASE.tar.bz2
 - tar xfj $HARFBUZZ_BASE.tar.bz2 && pushd $HARFBUZZ_BASE
 - ./configure --with-graphite2=auto && make && make install && popd
   # Install SILE runtime dependencies
 - luarocks install lpeg
 - luarocks install luaexpat
 - luarocks install lua_cliargs 2.3-3
 - luarocks install busted
script:
 - ./bootstrap.sh && ./configure && make
 - busted -m './lua-libraries/?.lua;./lua-libraries/?/init.lua' tests
 - ./tests/attack.pl
 - ./tests/attack.pl --regression
