language: c
sudo: false
compiler:
 - gcc
addons:
 apt:
  packages:
   - libgraphite2-dev
   - libicu-dev
   - libreadline-dev
   - libfreetype6-dev
   - libfontconfig1-dev
   - libpng-dev
   - libexpat1-dev
env:
  global:
   - LUAROCKS=2.2.2
   - HARFBUZZ_BASE=harfbuzz-1.0.4
   - GRAPHITE=true
  matrix:
   - LUA=lua5.2
   - LUA=lua5.2 GRAPHITE=false
before_install:
 - mkdir ~/local/
 - source .travis/setenv_lua.sh
 - export LD_LIBRARY_PATH=$HOME/local/lib:$LD_LIBRARY_PATH
 - export LD_RUN_PATH=$HOME/local/lib:$LD_RUN_PATH
 - export PKG_CONFIG_PATH=$HOME/local/lib/pkgconfig:$PKG_CONFIG_PATH
 - echo $HOME/local/
 - mkdir ~/.fonts && pushd ~/.fonts/ && wget http://dealer.simon-cozens.org/~simon/tmp/silefonts.tar.gz && tar xvf silefonts.tar.gz && popd
 - mkdir ~/builddeps/ && pushd ~/builddeps/ && wget http://www.freedesktop.org/software/harfbuzz/release/$HARFBUZZ_BASE.tar.bz2
 - tar xfj $HARFBUZZ_BASE.tar.bz2 && cd $HARFBUZZ_BASE
 - ./configure --with-graphite2=auto --prefix=$HOME/local/ && make && make install && popd
   # Install SILE runtime dependencies
 - luarocks install lpeg
 - luarocks install luaexpat
 - luarocks install luafilesystem
 - luarocks install lua_cliargs 2.3-3
 - luarocks install busted
script:
 - ./bootstrap.sh && ./configure && make
 - busted -m './lua-libraries/?.lua;./lua-libraries/?/init.lua' tests
 - ./tests/attack.pl
 - ./tests/attack.pl --regression
