language: c
sudo: false
dist: xenial
branches:
  except:
    - appveyor
compiler:
 - gcc
addons:
 apt:
  packages:
   - pkg-config
   - bsdtar
   - libgraphite2-dev
   - libicu-dev
   - libreadline-dev
   - libssl-dev
   - libfreetype6-dev
   - libfontconfig1-dev
   - libpng-dev
   - libexpat1-dev
   - libipc-run-perl
env:
  global:
   - LUAROCKS=2.4.2
   - GRAPHITE=true
   - COVERAGE=false
   - MAKEFLAGS="--jobs=4"
  matrix:
   - LUA=lua5.3 HARFBUZZ=2.5.1 COVERAGE=true
   - LUA=lua5.3 HARFBUZZ=1.4.2
   - LUA=lua5.3 HARFBUZZ=1.1.3
   - LUA=lua5.2 HARFBUZZ=2.5.1
   - LUA=lua5.1 HARFBUZZ=2.5.1
   - LUA=luajit HARFBUZZ=2.5.1
cache:
  directories:
  - $HOME/local
  - $HOME/.lua
  - $HOME/.luarocks
  - $TRAVIS_BUILD_DIR/.fonts
  - $TRAVIS_BUILD_DIR/lua_modules
  - $TRAVIS_BUILD_DIR/libtexpdf
before_install:
 - export PATH=.travis:$HOME/.lua:$PATH:$HOME/.local/bin:$HOME/.luarocks/bin
 - export LUA_HOME_DIR=$HOME/local/lua
 - export LR_HOME_DIR=$HOME/.luarocks
 - bash .travis/setup_lua.sh
 - eval $(luarocks --tree lua_modules --local path)
 - export LD_LIBRARY_PATH=$HOME/local/lib:$LUA_HOME_DIR/lib:$LD_LIBRARY_PATH
 - export LIBRARY_PATH=$HOME/local/lib:$LUA_HOME_DIR/lib:$LD_LIBRARY_PATH
 - export LD_RUN_PATH=$HOME/local/lib:$LUA_HOME_DIR/lib:$LD_RUN_PATH
 - export PKG_CONFIG_PATH=$HOME/local/lib/pkgconfig:$PKG_CONFIG_PATH
 - export LUA=~/.lua/lua
 - export LUA_INCLUDE=-I$LUA_HOME_DIR/include
 - bash .travis/setup_harfbuzz.sh
install:
 - luarocks install busted
 - luarocks install luacov 0.8-1
 - luarocks install luacov-coveralls
before_scipt:
 - eval $(luarocks --tree lua_modules --local path)
script:
 - fold_unless_fail 'Building' 'build' sh -c './bootstrap.sh && ./configure && make'
 - fold_unless_fail 'Busted' 'busted'  make busted
 - fold_unless_fail 'Run regression tests' 'regression' make --output-sync test
 - fold_unless_fail 'Compile documentation and examples' 'compile_docs' make --output-sync docs examples
after_success:
 - $COVERAGE && travis_wait make coverage
 - $COVERAGE && travis_wait luacov-coveralls -e lua-libraries -e lua_modules
