language: c
matrix:
  include:
    - dist: precise
      sudo: false
    - dist: trusty
      sudo: required
compiler:
 - gcc
addons:
 apt:
  packages:
   - libgraphite2-dev
   - libicu-dev
   - libreadline-dev
   - libfreetype6-dev
   - libfontconfig1-dev
   - libpng-dev
   - libexpat1-dev
env:
  global:
   - LUAROCKS=2.2.2
   - HARFBUZZ_BASE=harfbuzz-1.2.3
   - GRAPHITE=true
  matrix:
   - LUA=lua5.2
   - LUA=lua5.2 GRAPHITE=false
   - LUA=lua5.1
   - LUA=lua5.1 GRAPHITE=false
   - LUA=lua5.3
   - LUA=lua5.3 GRAPHITE=false
cache:
  directories:
  - $HOME/.fonts
  - $HOME/local
  # Cache object files etc. to speed up build
  - $TRAVIS_BUILD_DIR/libtexpdf
before_install:
 - source .travis/setenv_lua.sh
 - export LD_LIBRARY_PATH=$HOME/local/lib:$LD_LIBRARY_PATH
 - export LIBRARY_PATH=$HOME/local/lib:$LD_LIBRARY_PATH
 - export LD_RUN_PATH=$HOME/local/lib:$LD_RUN_PATH
 - export PKG_CONFIG_PATH=$HOME/local/lib/pkgconfig:$PKG_CONFIG_PATH
 - if [ ! -f ~/.fonts/Scheherazade-R.ttf ]; then
      pushd ~/.fonts/ ;
      wget http://dealer.simon-cozens.org/~simon/tmp/silefonts.tar.gz ;
      tar xvf silefonts.tar.gz ;
      popd ;
   fi
 - if [ ! -f ~/local/include/harfbuzz/hb.h ]; then
      mkdir ~/local/ || true;
      mkdir ~/builddeps / || true;
      pushd ~/builddeps/ ;
      wget http://www.freedesktop.org/software/harfbuzz/release/$HARFBUZZ_BASE.tar.bz2 ;
      tar xfj $HARFBUZZ_BASE.tar.bz2 ;
      cd $HARFBUZZ_BASE ;
      if [ "x$GRAPHITE" = "xtrue" ]; then
         ./configure --with-graphite2=yes --prefix=$HOME/local/ ;
      else
         ./configure --with-graphite2=no --prefix=$HOME/local/ ;
      fi ;
      make ;
      make install ;
      popd ;
   fi
 - export LUA_HOME_DIR=$TRAVIS_BUILD_DIR/install/lua
 - export LUA=~/.lua/lua
 - export LUA_INCLUDE=-I$LUA_HOME_DIR/include
 - export LD_LIBRARY_PATH=$LUA_HOME_DIR/lib:$LD_LIBRARY_PATH
 - export LIBRARY_PATH=$LUA_HOME_DIR/lib:$LD_LIBRARY_PATH
 - export LD_RUN_PATH=$LUA_HOME_DIR/lib:$LD_RUN_PATH
install:
 - luarocks install lpeg
 - luarocks install luaexpat
 - luarocks install luafilesystem
 - luarocks install lua_cliargs 2.3-3
 - luarocks install busted
 - luarocks install luacov 0.8-1
 - luarocks install luacov-coveralls
script:
 - ./bootstrap.sh && ./configure && make
 - busted -m './lua-libraries/?.lua;./lua-libraries/?/init.lua' tests
 - ./tests/attack.pl
 - ./tests/attack.pl --regression --coverage
 - ./sile --debug=fonts,versions tests/bug-117.sil

after_success:
  - luacov-coveralls -e lua.libraries
